version: '1'
services:
  ms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@jy40lqe4n7i860ud_tp?TNS_ADMIN=/app/oracle_wallet/
      - spring.datasource.username=BJARAMILLO
      - spring.datasource.password=OracleCloud123
    restart: always